# Generated by Django 3.1.5 on 2021-01-21 20:30

from django.db import migrations, models
import django.db.models.deletion
import sheets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commits',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('CommittedDate', models.TextField(null=True)),
                ('VendorEmail', models.TextField(null=True)),
                ('VendorName', models.TextField(null=True)),
                ('VendorPhone', models.TextField(null=True)),
                ('ItemDescription', models.TextField(null=True)),
                ('ItemURL', models.TextField(null=True)),
                ('QTYCommitted', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'commits',
            },
        ),
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('ItemDescription', models.TextField(null=True)),
                ('ItemURL', models.TextField(null=True)),
                ('Price', models.FloatField(null=True)),
                ('PricePaying', models.FloatField(null=True)),
                ('Comment', models.TextField(null=True)),
                ('QTYPerOrder', models.IntegerField(null=True)),
                ('QTYWanted', models.IntegerField(null=True)),
                ('QTYCommitted', models.IntegerField(null=True)),
                ('QTYRemaining', models.IntegerField(null=True)),
                ('Filled', models.TextField(null=True)),
                ('Completed', models.BooleanField(null=True)),
                ('DateCreated', models.TextField(null=True)),
                ('DateCompleted', models.TextField(null=True)),
            ],
            options={
                'db_table': 'deals',
            },
        ),
        migrations.CreateModel(
            name='CommitsLog',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False, unique=True)),
                ('CommittedDate', models.TextField(null=True)),
                ('VendorEmail', models.TextField(null=True)),
                ('VendorName', models.TextField(null=True)),
                ('VendorPhone', models.TextField(null=True)),
                ('ItemDescription', models.TextField(null=True)),
                ('ItemURL', models.TextField(null=True)),
                ('QTYCommitted', models.IntegerField(null=True)),
                ('RelatedCommit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commit_history', to='sheets.commits')),
            ],
            options={
                'db_table': 'commits_log',
            },
        ),
        migrations.AddField(
            model_name='commits',
            name='Deal',
            field=models.ForeignKey(null=True, on_delete=models.SET(sheets.models.get_deleted_deal), related_name='deal_commits', to='sheets.deals'),
        ),
    ]
